site_name: MBARI-WEC
site_url: https://example.com/
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Buoy Control and Telemetry: ControlAndTelemetry.md
  - ROS2 Interface: ros2.md
  - Simulation: simulation.md
  - At Sea Operation: atseaoperation.md
  - Tutorials: tutorials.md
  - Theory: theory.md
  - Resources: resources.md
  - License: license.md
  - How to Cite: citation.md
  - Project Roadmap: roadmap.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
#  - pymdownx.highlight:
#      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme: readthedocs
