site_name: MBARI-WEC
site_url: https://example.com/
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Buoy Control and Telemetry: ControlAndTelemetry.md
  - At Sea Operation: atseaoperation.md
  - ROS 2 Interface: ros2.md
  - Simulation: simulation.md
  - Tutorials: tutorials.md
  - Theory: theory.md
  - Resources: resources.md
  - License: license.md
  - How to Cite: citation.md
  - Project Roadmap: roadmap.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/extra.js

markdown_extensions:
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name:
    "material"
  features:
    content.code.copy
